Fixup 6ac62fef5caba52cbfa71c093b242a1f0b5a1b88
Drop unused catkin_python_setup().
The call and setup.py are only required when defining python modules,
but jsk_recognition_msgs does not expose a python package (aside from
the autogenerated package for the messages).

This got noticed because Debian's python setuptools complains about
missing package list in setup.py:

---
error: Multiple top-level packages discovered in a flat-layout: ['srv', 'msg', 'debian', 'action', 'sample'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.
CMake Error at catkin_generated/safe_execute_install.cmake:4 (message):

  execute_process(/<<BUILDDIR>>package/.obj-x86_64-linux-gnu/catkin_generated/python_distutils_install.sh)
  returned error code
Call Stack (most recent call first):
  cmake_install.cmake:46 (include)
---