sound_classification requires catkin_virtualenv >= 0.3.0, see https://github.com/jsk-ros-pkg/jsk_recognition/pull/2635/checks?check_run_id=3936631517 for error logs
RuntimeError: Invalid requirement version 5.0.0,<7.0.0, must match ^[0-9\.]+$