Replace color.pyx with color.py for better compatibility
**Why?**

Currently, color.pyx is compiled with Cython and it is compatible only
with the Python version that is compiled with.
This is inconvenient when we want to use virtual environment (e.g.,
Anaconda) and run `import jsk_recognition_utils` in it (since `color`
module is imported in `jsk_recognition_utils.__init__`).

**Actual error?**

When I `import jsk_recognition_utils` from Python 3.7.X on Ubuntu 20.04
(where default Python3 is Python 3.8.10):

```
/home/wkentaro/projectX/.anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.8 of module 'jsk_recognition_utils.color' does not match runtime version 3.7
return f(*args, **kwds)
Traceback (most recent call last):
File "/home/wkentaro/projectX/ros/src/morefusion/ros/morefusion_panda_ycb_video/nodes/tile_image.py", line 8, in <module>
import jsk_recognition_utils
File "/opt/ros/noetic/lib/python3/dist-packages/jsk_recognition_utils/init.py", line 2, in <module>
from jsk_recognition_utils import color
File "type.pxd", line 9, in init jsk_recognition_utils.color
ValueError: builtins.type size changed, may indicate binary incompatibility. Expected 880 from C header, got 864 from PyObject
```

**Context**

The reason why it was originally implemented with Cython was because
there was 2 nested for-loop in
`jsk_recognition_utils.color.label_colormap`. However, I reimplemented
the same functionality using Numpy operation (no for-loops), so we
probably don't need to use Cython anymore.