skip deep_sort_tracker.test on indigo
https://travis-ci.org/jsk-ros-pkg/jsk_recognition/jobs/549216064#L8697-L8733

downloading SSD data(ssd300_voc0712_converted_2017_06_06.npz) failes with
```
 IOError: [Errno socket error] [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'
```

do we need to update Python to 2.7.9? for indidgo ????

https://stackoverflow.com/questions/54413685/insecureplatform-warning